name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: macos-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install dpkg ldid

      - name: Setup Theos & SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          
          # Dọn dẹp và tải bộ SDKs chuẩn
          rm -rf $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks

      - name: Build Tweak
        run: |
          export THEOS=$HOME/theos
          make clean
          make FINALPACKAGE=1

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-Dylib 
          path: |
            .theos/obj/*.dylib
            .theos/obj/debug/*.dylib
            packages/*.deb
