name: Build Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          make clean
          make FINALPACKAGE=1

      - name: Find and Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-Dylib
          path: .theos/obj/debug/AutoClicker.dylib
